[OnlineServices]
DefaultServices=Epic
bHasVoiceEnabled=true

[OnlineServices.EOS]
bEnabled=true
bEASAuthEnabled=false
Drivers=EOS
ProductId=5736169f306b4ed3934915c387fbebd8
SandboxId=p-2uwr9r4e8swhtk976znxuqhaxf4ja3
DeploymentId=3db15cd9844b4716b0486fabbdb8710a
ClientId=xyza78913FAzVNfW1gRouZfjLTUAtMDH
ClientSecret=HXP7UWVk1qvhVdJC0KWpvYqkS3kMNRJ6k/jwGZOE4ag

[OnlineServices.EOS.Auth]
DevAuthToolAddress=127.0.0.1:9000

[OnlineServices.Lobbies]
; We use lowercase 'gamelobby' to match the Log error
+SchemaDescriptors=(Id="gamelobby", ParentId="LobbyBase")
+SchemaAttributeDescriptors=(Id="BucketId", Type="string", Flags=(Public), MaxSize=64)
+SchemaAttributeDescriptors=(Id="ServerIP", Type="string", Flags=(Public), MaxSize=64)
+SchemaCategoryAttributeDescriptors=(SchemaId="gamelobby", CategoryId="Lobby", AttributeIds=("BucketId", "ServerIP"))

[OnlineServices.Sessions]
; We use lowercase 'gamesession' for safety
+SchemaDescriptors=(Id="gamesession", ParentId="SessionBase")
+SchemaAttributeDescriptors=(Id="BucketId", Type="string", Flags=(Public), MaxSize=64)
+SchemaAttributeDescriptors=(Id="ServerIP", Type="string", Flags=(Public), MaxSize=64)
+SchemaCategoryAttributeDescriptors=(SchemaId="gamesession", CategoryId="Session", AttributeIds=("BucketId", "ServerIP"))

[OnlineServices.EOS.Sessions]
bIsUsingP2PSessions=false

[/Script/OnlineSubsystemUtils.IpNetDriver]
NetServerMaxTickRate=60

[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/Level/Lobby_Level.Lobby_Level
GameDefaultMap=/Game/Level/Lobby_Level.Lobby_Level
ServerDefaultMap=/Game/Level/Museum_Level.Museum_Level

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=E3239BD34BA7FDA8EFA38ABC4EAD6973
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

